services:
  - type: web
    name: llama-api
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8000
